env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules: {
  "@typescript-eslint/indent": "off",
  "no-extra-semi": "off",
  "@typescript-eslint/consistent-type-assertions": "off",
  "@typescript-eslint/no-non-null-assertion": "off",
  "@typescript-eslint/strict-boolean-expressions": "off",
  "@typescript-eslint/semi": ["error", "always"],
  "@typescript-eslint/member-delimiter-style":"off",
  "@typescript-eslint/space-before-function-paren":"off",
  "no-template-curly-in-string": "off",
  "@typescript-eslint/comma-dangle": "off",
  "comma-dangle": "off"
}
