openapi: 3.0.1
info:
  title: Echo Server 
  description: This is a simple example of an echo server
  version: 1.0.0
paths:
  /echo/:path: 
    get:
      operationId: echoRequest
      parameters:
        - name: path
          in: path
          required: true
          schema: 
            type: string
        - name: query
          in: query
          required: false 
          schema: 
            type: string
      
      responses:
        200:
          description: Successful response
          content:
            application/json: 
              schema:
                "$ref": "#/components/schemas/EchoResponse"  
    post:
      operationId: echoPostRequest
      parameters:
        - name: path
          in: path
          required: true
          schema: 
            type: string
     
      requestBody:
         content:
           application/json:
            schema: 
              "$ref": "#/components/schemas/ArbitaryRequestBody"  
      responses:
        200:
          description: Successful response
          content:
            application/json: 
              schema:
                "$ref": "#/components/schemas/EchoResponse"  

components:
  schemas:
    ArbitaryRequestBody:
      type: object
      additionalProperties: true
    EchoResponse:
      type: object
      properties:
        path:
          type: array
          items:
            $ref: "#/components/schemas/RequestParameter"
        query:
          type: array
          items:
            $ref: "#/components/schemas/RequestParameter"
      
    RequestParameter:
      type: object
      properties:
        key:
          type: string
        value:
          type: string 