name: Quality Gates

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - uses: actions/setup-node
        with:
          node-version: '20'

      - run: yarn install
        name: Install

      - run: yarn lint
        name: Lint

      - run: yarn ci --max-workers ${{ steps.cpu-cores.outputs.count }}
        name: Test
