name: Quality Gates

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test
      - run: yarn coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov-report
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - uses: codecov/codecov-action@v1
        with:
          path: coverage/lcov-report